### ISSUE TITLE
smartctl with sat driver

### ISSUE THREAD

**Issue by notti** [sometimesfood/diskburn#1]
https://github.com/sometimesfood/diskburn/blob/2c1de0c290219eea7d163bcb0d98df019eb88e1d/diskburn#L41
https://github.com/sometimesfood/diskburn/blob/2c1de0c290219eea7d163bcb0d98df019eb88e1d/diskburn#L94
https://github.com/sometimesfood/diskburn/blob/2c1de0c290219eea7d163bcb0d98df019eb88e1d/diskburn#L115

Any particular reason this has the scsi-to-ata translation driver (sat) as default?
 -> this fails with scsi (sas) devices

**Comment by sometimesfood** [comment]
This is due to historical reasons. If you send me a pull request to remove the "-d" option , I'd be happy to merge it.
